### ISSUE TITLE
Playlist SQL Creation Tool

### ISSUE THREAD

**Issue by spaceangel1970** [fordcrews/PopperTools#1]
I have tried using this but it doesn't seem to show the full list for the playlists that are in popper. This would be a useful tool..

**Comment by fordcrews** [comment]
I added some debug logic, it should show more of what it's doing to see why it isn't pulling them for you.

**Comment by spaceangel1970** [comment]
I Just tried it again with PUP Packs in TAGS it is saying there is one table when there is acttually 240.
![Screenshot 2024-07-17 061816](https://github.com/user-attachments/assets/e5e69a3c-5e37-49d8-8022-c15f4dca5aed)
![Screenshot 2024-07-17 061930](https://github.com/user-attachments/assets/776b1776-2052-4ac0-9fd8-3463087582d9)

**Comment by fordcrews** [comment]
I'll look at it tomorrow, my cabinet is torn apart, I'm changing some led's.   I may have to figure out how to get a copy of your .db file to duplicate what is going on.

**Comment by spaceangel1970** [comment]
I have attached my DB file thanks for getting back to me..
[PUPDatabase.zip](https://github.com/user-attachments/files/16257874/PUPDatabase.zip)

**Comment by fordcrews** [comment]
Cool, I'm crosseyed, will look at it tomorrow.

**Comment by fordcrews** [comment]
Ok, You will have to get the new python and index.html.    I wasn't accounting for that tags, authors, and several other groups, had tag,tag,tag or author, author, author in them.   Now I separate them and group them by the separated values.

**Comment by spaceangel1970** [comment]
Updated everything, now works a treat thanks for your help much appreciated and keep up the good work.....

**Comment by fordcrews** [comment]
Glad to help
